// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKENoeIOBW7FECbwYV1cmoxkpcmQ5nL0',
    appId: '1:357504917396:web:6eac703884c8455bac3981',
    messagingSenderId: '357504917396',
    projectId: 'silver-charmer-444401-m2',
    authDomain: 'silver-charmer-444401-m2.firebaseapp.com',
    storageBucket: 'silver-charmer-444401-m2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOVApBTVmNvOZn3OKBj5LadUOlPG7FoU',
    appId: '1:357504917396:android:edd186f2e60c96c6ac3981',
    messagingSenderId: '357504917396',
    projectId: 'silver-charmer-444401-m2',
    storageBucket: 'silver-charmer-444401-m2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VunVkXp8ODeg60p9sfNuV3ZSi7sjDlA',
    appId: '1:357504917396:ios:3a7100a8743dd512ac3981',
    messagingSenderId: '357504917396',
    projectId: 'silver-charmer-444401-m2',
    storageBucket: 'silver-charmer-444401-m2.firebasestorage.app',
    androidClientId: '357504917396-nvtgktig9j2lmamg1op0nv2d2v4do3en.apps.googleusercontent.com',
    iosClientId: '357504917396-27osrfargvqcgpm4b7m7kfmbjav48mcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VunVkXp8ODeg60p9sfNuV3ZSi7sjDlA',
    appId: '1:357504917396:ios:3a7100a8743dd512ac3981',
    messagingSenderId: '357504917396',
    projectId: 'silver-charmer-444401-m2',
    storageBucket: 'silver-charmer-444401-m2.firebasestorage.app',
    androidClientId: '357504917396-nvtgktig9j2lmamg1op0nv2d2v4do3en.apps.googleusercontent.com',
    iosClientId: '357504917396-27osrfargvqcgpm4b7m7kfmbjav48mcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKENoeIOBW7FECbwYV1cmoxkpcmQ5nL0',
    appId: '1:357504917396:web:734d2fa6385a6883ac3981',
    messagingSenderId: '357504917396',
    projectId: 'silver-charmer-444401-m2',
    authDomain: 'silver-charmer-444401-m2.firebaseapp.com',
    storageBucket: 'silver-charmer-444401-m2.firebasestorage.app',
  );
}
